ALTER TABLE contentFile
ALTER COLUMN fileBlob blob;
ALTER TABLE contentFile
ALTER COLUMN thumbBlob varbinary(max);

ALTER TABLE valueFile
ALTER COLUMN imageBlob varbinary(max);
ALTER TABLE valueFile
ALTER COLUMN thumbBlob varbinary(max);

ALTER TABLE template
ALTER COLUMN displayCode varchar(max);

Insert into Constant 
VALUES 
('itemsPerPage','10',1,0,1),
('uploadFileTypes','application/pdf',1,0,1),
('uploadImageTypes','image/jpeg,image/gif,image/png',1,0,1),
('fileInhaleThreshold','524288',1,0,1),
('assetStore','C:\inetpub\wwwroot\NZRugby\assets\store\',1,1,1),
('Website Root','C:\inetpub\wwwroot\NZRugby\',1,1,0);


INSERT INTO Action
VALUES
	('Read',1,1),
	('Write',1,1),
	('Delete',1,1),
	('Publish',1,0);

INSERT INTO Role
VALUES
	('Admin',1,1),
	('SuperUser',1,1),
	('Editor',1,1),
	('Publisher',1,0),
	('Guest',1,0);

INSERT INTO category
VALUES
	('Technical Debt'),
	('JQuery'),
	('Usability'),
	('Security'),
	('Framework'),
	('eCommerce')
	;
	
	
INSERT INTO [admin]
VALUES
	('marty', 'vEiKTjOTZZXRmxGYa0ehIe9KCfGQL78ECrFVDxXky90=',  'A552521DEDC907830D283CAEEB9FDE27E2725DAA120970364F61A8263575ED21C8DC1E22F5104AE5A710A3AF38FD698649E24F22BAAD67EA7CEAD205666CE220', '1',1);
	

INSERT INTO Tag
VALUES
	('Content', 1),
	('Text', 1),
	('Image', 1),
	('Page', 1),
	('Template', 1),
	('Common', 1);
 
INSERT INTO mimeType
VALUES
('.bmp','image/bmp','contentImage'),
('.bmp','image/x-windows-bmp','contentImage'),
('.css','text/css','contentFile'),
('.gif','image/gif','contentImage'),
('.htm','text/html','contentFile'),
('.html','text/html','contentFile'),
('.jpe','image/jpeg','contentImage'),
('.jpe','image/pjpeg','contentImage'),
('.jpeg','image/jpeg','contentImage'),
('.jpeg','image/pjpeg','contentImage'),
('.jpg','image/jpeg','contentImage'),
('.jpg','image/pjpeg','contentImage'),
('.mov','video/quicktime',null),
('.mp2','audio/mpeg',null),
('.mp2','audio/x-mpeg',null),
('.mp2','video/mpeg',null),
('.mp2','video/x-mpeg',null),
('.mp2','video/x-mpeq2a',null),
('.mp3','audio/mpeg3',null),
('.mp3','audio/x-mpeg-3',null),
('.mp3','video/mpeg',null),
('.mp3','video/x-mpeg',null),
('.pdf','application/pdf','contentFile'),
('.png','image/png','contentImage'),
('.text','text/plain','contentFile'),
('.txt','text/plain','contentFile');



insert into glyph
VALUES
('asterisk'),
('plus'),
('euro'),
('minus'),
('cloud'),
('envelope'),
('pencil'),
('glass'),
('music'),
('search'),
('heart'),
('star'),
('star-empty'),
('user'),
('film'),
('th-large'),
('th'),
('th-list'),
('ok'),
('remove'),
('zoom-in'),
('zoom-out'),
('off'),
('signal'),
('cog'),
('trash'),
('home'),
('file'),
('time'),
('road'),
('download-alt'),
('download'),
('upload'),
('inbox'),
('play-circle'),
('repeat'),
('refresh'),
('list-alt'),
('lock'),
('flag'),
('headphones'),
('volume-off'),
('volume-down'),
('volume-up'),
('qrcode'),
('barcode'),
('tag'),
('tags'),
('book'),
('bookmark'),
('print'),
('camera'),
('font'),
('bold'),
('italic'),
('text-height'),
('text-width'),
('align-left'),
('align-center'),
('align-right'),
('align-justify'),
('list'),
('indent-left'),
('indent-right'),
('facetime-video'),
('picture'),
('map-marker'),
('adjust'),
('tint'),
('edit'),
('share'),
('check'),
('move'),
('step-backward'),
('fast-backward'),
('backward'),
('play'),
('pause'),
('stop'),
('forward'),
('fast-forward'),
('step-forward'),
('eject'),
('chevron-left'),
('chevron-right'),
('plus-sign'),
('minus-sign'),
('remove-sign'),
('ok-sign'),
('question-sign'),
('info-sign'),
('screenshot'),
('remove-circle'),
('ok-circle'),
('ban-circle'),
('arrow-left'),
('arrow-right'),
('arrow-up'),
('arrow-down'),
('share-alt'),
('resize-full'),
('resize-small'),
('exclamation-sign'),
('gift'),
('leaf'),
('fire'),
('eye-open'),
('eye-close'),
('warning-sign'),
('plane'),
('calendar'),
('random'),
('comment'),
('magnet'),
('chevron-up'),
('chevron-down'),
('retweet'),
('shopping-cart'),
('folder-close'),
('folder-open'),
('resize-vertical'),
('resize-horizontal'),
('hdd'),
('bullhorn'),
('bell'),
('certificate'),
('thumbs-up'),
('thumbs-down'),
('hand-right'),
('hand-left'),
('hand-up'),
('hand-down'),
('circle-arrow-right'),
('circle-arrow-left'),
('circle-arrow-up'),
('circle-arrow-down'),
('globe'),
('wrench'),
('tasks'),
('filter'),
('briefcase'),
('fullscreen'),
('dashboard'),
('paperclip'),
('heart-empty'),
('link'),
('phone'),
('pushpin'),
('usd'),
('gbp'),
('sort'),
('sort-by-alphabet'),
('sort-by-alphabet-alt'),
('sort-by-order'),
('sort-by-order-alt'),
('sort-by-attributes'),
('sort-by-attributes-alt'),
('unchecked'),
('expand'),
('collapse-down'),
('collapse-up'),
('log-in'),
('flash'),
('log-out'),
('new-window'),
('record'),
('save'),
('open'),
('saved'),
('import'),
('export'),
('send'),
('floppy-disk'),
('floppy-saved'),
('floppy-remove'),
('floppy-save'),
('floppy-open'),
('credit-card'),
('transfer'),
('cutlery'),
('header'),
('compressed'),
('earphone'),
('phone-alt'),
('tower'),
('stats'),
('sd-video'),
('hd-video'),
('subtitles'),
('sound-stereo'),
('sound-dolby'),
('sound-5-1'),
('sound-6-1'),
('sound-7-1'),
('copyright-mark'),
('registration-mark'),
('cloud-download'),
('cloud-upload'),
('tree-conifer'),
('tree-deciduous');

INSERT INTO lorum
VALUES
('Lorem ipsum dolor sit amet, consectetur adipiscing elit. In fermentum nec mauris vitae dapibus. In et elementum quam, vel ornare elit. Morbi imperdiet, justo vel viverra tincidunt, turpis elit volutpat risus, non tempor quam nisl feugiat risus. Aliquam nec condimentum ante. Integer commodo accumsan lorem id vestibulum. Cras hendrerit pretium sagittis. Etiam id varius felis, id feugiat nibh. Vestibulum vitae ultricies quam. Praesent ut mollis nunc. Suspendisse sagittis dui eu nunc condimentum, tempor euismod urna euismod. Proin lacinia sed arcu vitae pretium. Morbi convallis mi nibh, ac pharetra metus bibendum quis. In hac habitasse platea dictumst. Mauris vel venenatis metus, ut eleifend mauris. Praesent ullamcorper ultrices lectus, quis aliquam turpis euismod nec. Nunc cursus convallis dictum.'),
('Aenean est lacus, condimentum quis velit in, euismod posuere erat. Quisque justo urna, pretium et vulputate et, ultricies sit amet odio. Pellentesque vel feugiat tellus, sed molestie nisi. Sed ut ornare urna. Cras pretium condimentum convallis. Ut urna risus, commodo ut porttitor at, varius id purus. Curabitur gravida ipsum ac dolor rutrum, et aliquam nisl sodales. Praesent iaculis libero id blandit hendrerit. Proin faucibus vitae sapien a blandit. Nunc pellentesque gravida felis sed hendrerit.'),
('Fusce vitae magna et sem viverra consectetur. Maecenas tincidunt mi ut elementum lacinia. Sed ac velit iaculis, molestie massa eu, tempor nibh. In nec dui quis urna tincidunt fermentum at sit amet ipsum. Maecenas commodo ante in dolor pulvinar, et gravida urna auctor. Aliquam feugiat arcu sed elit sodales hendrerit id vel lacus. Sed magna nulla, rhoncus sit amet semper id, aliquam vel ipsum. Fusce justo lectus, facilisis id augue at, dictum rhoncus justo. Duis nec vehicula mi. Aenean at sem facilisis, pellentesque ligula vitae, ullamcorper diam. Duis mollis leo at fringilla ornare. Cras enim magna, facilisis a fringilla a, malesuada eu justo. Praesent malesuada nisl metus, vel venenatis ante condimentum et. Sed quis molestie felis. Vestibulum ultricies, purus gravida imperdiet posuere, nisi tortor mattis diam, a facilisis est quam sit amet arcu.'),
('Phasellus adipiscing tincidunt diam, ut dictum nunc varius sed. Vestibulum sodales est ullamcorper, elementum augue eget, malesuada felis. Maecenas luctus tincidunt tortor eget elementum. Sed vitae orci justo. Pellentesque eget nisi in nisi ultrices cursus. Sed quis lacus nisi. Donec convallis sollicitudin nibh, ut molestie nulla. Proin diam nibh, fermentum quis ipsum non, ultrices semper arcu. Donec sit amet dapibus ante. Morbi tempor sem et turpis placerat consequat. Etiam in cursus tortor. Aenean ut fringilla neque. Curabitur ornare, eros sit amet dictum venenatis, lectus ligula suscipit nisl, quis vehicula nulla odio blandit felis.'),
('Suspendisse mattis fermentum semper. Integer vitae placerat mi. Phasellus ac mauris mauris. Quisque sit amet sapien consequat, porta sem nec, pulvinar urna. Nunc imperdiet magna ac urna tempor, at pulvinar magna ornare. Phasellus rhoncus placerat consectetur. Duis nec nunc magna. In sed justo eget ante venenatis dapibus id id orci. Integer vitae consectetur felis, ut mollis elit. Aliquam tristique orci bibendum feugiat vulputate. Curabitur volutpat lorem vitae dolor semper, sit amet sodales purus hendrerit. Phasellus nisi nisi, facilisis at venenatis sit amet, vestibulum et lorem. Proin varius sem sed felis commodo, sed sollicitudin felis venenatis.'),
('Vestibulum sodales varius felis, eu hendrerit nibh. Fusce feugiat convallis sapien, eget fringilla eros hendrerit vitae. Nunc ac dictum quam. Cras tristique lorem ac ante rhoncus, vel lobortis sapien laoreet. Vestibulum est arcu, tempus vel adipiscing vitae, consequat in ipsum. Sed eu justo vel metus tempus interdum. Pellentesque pretium lectus eros, ut consectetur risus varius eu.'),
('Curabitur eu dolor ante. Duis a pretium risus, eget condimentum sem. Nunc cursus eleifend vestibulum. Cras sit amet dapibus augue. Mauris nec porttitor leo, non tristique velit. Donec pretium tellus urna, ut tempus lectus mattis consequat. Suspendisse iaculis tincidunt sem, eget auctor orci sagittis id.'),
('Maecenas nec sodales lectus. Sed iaculis sollicitudin fermentum. Cras porttitor at risus sed porttitor. Proin gravida mauris at cursus elementum. Nullam eu magna ac leo pellentesque varius. Praesent in purus vestibulum, interdum elit vitae, sodales ipsum. Sed sit amet urna purus. Aenean suscipit viverra lorem, convallis imperdiet nisl fringilla eu. Vivamus neque turpis, dictum vel cursus et, dictum a est. Vivamus condimentum suscipit congue. Aenean eu accumsan tortor, sed porttitor massa. Maecenas eget laoreet arcu. Duis vulputate fringilla neque quis molestie. Curabitur sed pharetra neque, suscipit accumsan velit. Aliquam justo metus, consequat ut lobortis sit amet, pellentesque sit amet quam. Vivamus accumsan interdum lorem ut gravida.'),
('Cras leo metus, feugiat nec felis pretium, laoreet tincidunt metus. Fusce consectetur nibh a faucibus faucibus. Praesent non metus leo. Curabitur consequat rhoncus tempus. Duis est ligula, interdum eu turpis at, aliquam ullamcorper mi. Quisque est augue, mollis vel vestibulum adipiscing, tempus at lorem. Nulla ac purus dictum, viverra metus ac, tincidunt tellus. Nam aliquam metus at volutpat elementum.'),
('Quisque lobortis tortor risus, nec condimentum nunc iaculis et. Nulla consequat lectus sed ipsum vulputate bibendum. In vel cursus neque, quis sollicitudin orci. Praesent placerat imperdiet pellentesque. In vel dignissim sapien. Duis sed auctor est. Integer sodales eget neque sed malesuada. Maecenas tincidunt enim eget gravida accumsan. Proin leo ante, blandit id risus vel, porttitor lobortis erat. Nullam non eros massa. Sed at pellentesque elit. Nunc ut varius tortor. Vestibulum varius posuere massa eget sollicitudin. Mauris luctus nisi velit, eu tincidunt purus iaculis consequat. Integer consequat nibh erat, id pellentesque mi tempus eu. Proin ac accumsan arcu, quis elementum arcu.'),
('Donec enim neque, facilisis nec malesuada quis, tempus non tellus. Quisque sit amet eros pharetra, cursus lacus eget, fringilla magna. Curabitur dictum arcu nec nisi cursus, eget lobortis elit adipiscing. Donec aliquam eros a egestas hendrerit. Cras in magna vitae arcu sollicitudin accumsan. Aenean eget ante elit. Fusce placerat volutpat rutrum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Cras at lorem eget nisl ullamcorper tempus. Etiam eget euismod velit.'),
('Donec ullamcorper blandit turpis, sit amet tincidunt lacus bibendum quis. Vivamus tortor leo, sodales at augue accumsan, sollicitudin auctor ligula. Quisque rutrum felis massa, nec malesuada massa ornare commodo. Pellentesque auctor mi ligula, vel adipiscing nunc iaculis id. Praesent luctus, leo a auctor dapibus, sem magna posuere nibh, at laoreet dui ante vitae massa. Duis vel metus in nisl aliquam bibendum ut quis felis. Mauris nec sem feugiat, condimentum diam vel, luctus libero.'),
('Quisque ac pulvinar libero, nec pellentesque ante. Ut nisl est, ultricies ac auctor sit amet, cursus et eros. Duis id dictum mauris, et suscipit mauris. Proin nec urna id sapien accumsan elementum nec non sapien. In semper nisl lobortis, euismod sapien id, porttitor urna. Pellentesque interdum felis velit, vel fermentum nisl sagittis vel. Quisque varius, justo id hendrerit aliquet, augue mauris accumsan elit, non tristique sem mauris sit amet est. Donec venenatis lorem non leo volutpat hendrerit.'),
('Nulla tincidunt urna a elit elementum congue. Nam mauris est, lobortis ac consectetur sed, ullamcorper non nibh. Nam in interdum tortor. Morbi vel purus vitae quam molestie blandit a elementum leo. Fusce convallis velit lorem. Nulla blandit fermentum nisl, malesuada accumsan quam vestibulum sed. Nam interdum diam et eros ornare venenatis. Vestibulum posuere lectus a varius pellentesque. Donec blandit aliquam erat id aliquam. Quisque molestie blandit risus adipiscing volutpat. Vestibulum hendrerit elit est, nec laoreet metus faucibus a.'),
('In pretium libero in lorem consectetur venenatis. Curabitur ac molestie neque. Vestibulum non scelerisque lectus. Suspendisse adipiscing, dolor vel laoreet tempor, felis lacus molestie velit, nec interdum tortor enim sit amet mi. Nunc eget vestibulum lorem. Morbi tristique, turpis a lobortis lobortis, lacus felis sollicitudin augue, eget tristique lorem arcu lobortis velit. Suspendisse mattis nulla sed dictum adipiscing. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Pellentesque porttitor suscipit metus, nec iaculis sapien rutrum eget. Praesent non ultricies dolor, quis pretium odio. Duis placerat, mauris id lobortis lobortis, tellus magna gravida lorem, quis interdum lorem sapien in eros. Aenean quis tempus urna.'),
('Etiam pretium tincidunt consectetur. Donec congue eleifend porttitor. Nunc sagittis, odio adipiscing rhoncus ornare, velit arcu luctus magna, et fringilla justo eros eu ipsum. Aenean pretium sodales mattis. Phasellus lobortis eros libero, sed auctor nisl tincidunt in. Donec aliquet purus tempus hendrerit molestie. Pellentesque faucibus blandit magna, eu scelerisque diam elementum sed. Fusce ac enim magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi eget ante a mauris interdum vestibulum. Donec dui augue, pellentesque a nisl quis, cursus venenatis nisi.'),
('Sed elit urna, interdum quis nunc in, consectetur accumsan lectus. Pellentesque vulputate elit nunc, vitae pretium ante consectetur nec. Mauris placerat pharetra ligula nec vulputate. Donec accumsan luctus velit, ut tempus massa commodo posuere. Aenean bibendum semper enim, eget mollis nisi malesuada sed. Donec cursus mauris in lectus ullamcorper, nec lacinia augue mattis. Duis sed viverra dui. Vivamus facilisis purus vel lectus adipiscing, non iaculis est semper. In varius ullamcorper nibh, ut blandit erat sagittis at. Nulla porta pharetra augue, in luctus dui venenatis id. Fusce non mattis urna. Integer tincidunt justo ac ipsum aliquam suscipit. Cras ultrices sodales scelerisque.'),
('Sed aliquet, ante non fermentum vestibulum, nisl ipsum tempus purus, eget varius nibh orci in ante. Proin ante magna, pretium eget massa at, consectetur tristique tortor. Donec tellus diam, luctus fermentum feugiat nec, viverra ut massa. Ut vel ipsum dolor. Aliquam erat volutpat. Cras eget sollicitudin augue. Pellentesque egestas neque sit amet magna dapibus, ut vehicula turpis laoreet. Ut id ante metus. Nam risus dolor, pulvinar tempus quam quis, ultricies sodales felis. In feugiat eu justo in fermentum. Sed sed justo lorem. Suspendisse eros nibh, consectetur eget nunc non, consequat lobortis elit. Cras eu nisl mollis, rhoncus est eget, volutpat augue. Aliquam non bibendum sapien.'),
('Vivamus hendrerit risus non nisl tempus, quis tincidunt mi laoreet. Vivamus nec dui eu purus auctor rhoncus. Mauris sed eleifend odio. Vestibulum sit amet aliquet neque. Curabitur at erat in velit convallis dignissim. Mauris rutrum libero vitae aliquet pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas risus ligula, sagittis nec rhoncus quis, sollicitudin quis nisi. Aenean sed mauris a est eleifend eleifend sed nec dui. Etiam porta suscipit felis sit amet convallis. Nulla a nulla purus. Etiam ut orci nec eros vehicula ornare. Nulla laoreet nisi faucibus tempor lacinia.'),
('Nulla placerat scelerisque turpis, a dictum massa mattis commodo. Integer justo ante, elementum ut tortor non, viverra vehicula nisi. Etiam sit amet magna id sem suscipit ullamcorper. Ut id velit in erat rutrum eleifend. Ut sed elit interdum, viverra quam condimentum, pretium mauris. Nullam a bibendum ligula. Duis mattis turpis vitae mauris lacinia tempus. Suspendisse semper tortor et sapien interdum rutrum. Integer mi ligula, luctus nec nisl non, congue iaculis massa. Aliquam erat volutpat. Donec nec arcu nunc. Sed molestie sem quis justo tempus pharetra. Donec accumsan sollicitudin porttitor. Cras nec dignissim magna, nec pharetra enim. Vivamus lacinia aliquam enim id cursus.'),
('Praesent a vestibulum est. Nam gravida pharetra nibh, eget suscipit orci varius et. Integer tortor dui, tristique in convallis at, pharetra eu velit. Fusce commodo faucibus ornare. Praesent eu mi in nisi vulputate iaculis. Suspendisse vehicula orci eu ipsum sagittis dictum. Donec nec mauris dolor. Sed viverra hendrerit suscipit. In sed porttitor sem. Donec vitae lectus dapibus, egestas ante non, condimentum leo. Suspendisse quis erat libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Curabitur mollis posuere accumsan. Fusce at fringilla massa. Nunc accumsan, ipsum sit amet pretium egestas, ante nunc facilisis enim, non condimentum velit velit nec purus. Pellentesque porttitor tempor diam vitae interdum.'),
('Pellentesque consequat nisi lobortis tellus lacinia, vitae molestie urna aliquet. Donec hendrerit justo sed leo porta consectetur id vitae magna. Nunc dictum massa ut augue hendrerit, at vestibulum mi aliquam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec euismod quam vitae lorem varius consectetur. Praesent felis diam, volutpat sit amet facilisis quis, dapibus eget sapien. Morbi posuere tempus erat, quis fringilla libero dignissim placerat. Curabitur viverra elit sit amet lorem condimentum rhoncus quis a lorem. Vivamus tempus nisi massa, ac bibendum massa suscipit in.'),
('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in tincidunt tellus. Praesent lorem mi, pharetra vitae pretium et, vestibulum non sem. Cras fringilla mauris eleifend diam suscipit, ut viverra mi consequat. Suspendisse non velit lacinia, tempus magna at, sagittis lacus. Sed mattis commodo tortor at facilisis. Maecenas quam augue, facilisis a interdum nec, adipiscing ut nisi. Aliquam viverra porttitor enim sed ornare. In adipiscing rutrum lacus, sit amet hendrerit diam faucibus et. Quisque in commodo leo. Duis luctus velit in neque semper, interdum ultrices sem euismod.'),
('Donec sagittis sed arcu sed hendrerit. In nec urna vel nulla auctor congue eu ut ante. Donec iaculis blandit massa, quis venenatis ipsum ornare id. Nam eu enim at est pulvinar eleifend a vel nibh. Nulla sodales pharetra enim ut imperdiet. Vivamus sodales arcu id magna tincidunt lacinia. Pellentesque egestas cursus est quis lobortis. Cras eget sodales dolor, in facilisis orci. Nunc congue, nibh id molestie sodales, lectus diam commodo sapien, eu gravida lectus dui et massa.'),
('Integer vel sapien vel eros facilisis egestas nec nec erat. Aliquam sed est in purus euismod sagittis. Nulla facilisi. Donec nec nunc eget justo bibendum sodales. Nullam suscipit in neque a tempor. Phasellus volutpat mi eget odio lacinia iaculis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque non feugiat ante. Integer ullamcorper, dui nec venenatis scelerisque, arcu arcu eleifend sapien, id dapibus magna turpis ac felis.'),
('Integer vel nibh hendrerit, imperdiet nisi non, scelerisque tortor. In viverra libero id viverra interdum. Aliquam et sem mattis, cursus risus id, venenatis ligula. Cras ante arcu, gravida a feugiat sed, interdum id arcu. Morbi velit dolor, ultrices at velit sit amet, molestie suscipit neque. Integer pulvinar varius mauris eget vestibulum. Aenean sagittis eros sed venenatis mollis. Donec hendrerit purus sed sagittis malesuada. Proin nec convallis lacus, ac elementum ipsum. Maecenas lacus nisi, venenatis vel aliquet in, gravida ut libero. Sed ac enim sollicitudin erat ultrices porta ac et leo.'),
('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum nec varius nibh, sit amet ornare nisi. Fusce bibendum odio vel facilisis egestas. Nam ut tellus sed arcu pulvinar hendrerit. Pellentesque elit justo, lobortis sed nisl vitae, dignissim sagittis metus. Duis tempor neque vitae quam mattis, sit amet ultrices diam tempor. Quisque lacinia, ligula eu pharetra imperdiet, enim ligula accumsan lorem, vitae blandit enim sem quis orci. Nulla imperdiet fermentum erat, vel malesuada leo congue sit amet.'),
('Nam ut odio iaculis, tincidunt urna eu, tristique tellus. Nunc interdum tincidunt purus, condimentum pretium tellus vestibulum id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Ut non sem quis augue dictum gravida. In a lectus quis quam molestie consequat a ut purus. Etiam a nisl urna. Phasellus at viverra metus. Phasellus adipiscing nec elit mollis viverra. Nulla facilisi. Donec auctor sem vitae nisl luctus, eget faucibus arcu gravida.'),
('Curabitur massa magna, vulputate sit amet metus ac, fringilla faucibus massa. Integer eget ultricies tellus, at congue dolor. Curabitur non tincidunt ligula. Vestibulum ullamcorper at turpis eu condimentum. Sed vel tincidunt nisi, at euismod justo. Integer venenatis justo hendrerit arcu bibendum, sed viverra orci tincidunt. Integer id nibh lobortis diam iaculis dictum. Suspendisse vel molestie magna. Aenean sapien mauris, mollis ut nisl venenatis, facilisis posuere sapien. Etiam eros diam, dapibus non tortor sit amet, lacinia elementum odio. In vestibulum, tortor nec scelerisque tincidunt, ligula neque sollicitudin neque, id lacinia augue lorem nec arcu. Curabitur justo lectus, tempus vitae urna quis, porta eleifend nulla. Maecenas malesuada eros ipsum, quis pretium ipsum interdum ac. Cras cursus, eros sit amet feugiat interdum, eros turpis rutrum dolor, eget tincidunt sapien risus et nunc. Quisque vulputate sem at ipsum ultrices gravida. Nulla sit amet nisi in eros luctus rhoncus id eu ipsum.'),
('Vivamus sed quam tortor. Praesent dapibus facilisis interdum. Etiam accumsan id risus vel semper. Donec quis mi adipiscing, egestas arcu sit amet, pretium quam. Fusce sagittis porta libero eget congue. Nulla id mi a enim molestie auctor. Morbi lobortis accumsan odio, ut pretium mi euismod ut.'),
('Duis in magna congue, volutpat urna a, fringilla ligula. Nam vestibulum, leo eu tincidunt malesuada, lacus enim commodo mi, vitae condimentum mi mi ac nibh. Donec faucibus ac lorem pretium sodales. Fusce placerat metus dui, vel rhoncus nisi dignissim vel. Suspendisse congue porttitor nunc ut vehicula. Nulla bibendum purus eget leo pulvinar malesuada. Donec molestie ligula felis, sed suscipit purus mattis quis. Maecenas at lacinia turpis, eget aliquet justo. Duis tellus tellus, pellentesque in ultricies id, bibendum sit amet ipsum.'),
('Nunc luctus nec neque luctus viverra. Aliquam convallis, erat vitae pellentesque facilisis, dui mi lacinia odio, vel adipiscing leo risus id odio. Integer hendrerit erat vel risus dictum, vel dignissim leo tincidunt. Integer porttitor magna id volutpat egestas. Ut lacinia ultrices leo nec elementum. Nam interdum nulla eu libero ullamcorper lacinia. Donec a tortor ultricies, molestie mauris eget, egestas tellus. In posuere elit quis sodales lobortis. Praesent ac orci non nunc venenatis blandit elementum sed tortor.'),
('Curabitur aliquet tortor arcu, vel mattis nulla commodo a. Curabitur est mi, porttitor at dolor viverra, dapibus accumsan lorem. Fusce at tincidunt nulla. Curabitur vel ligula vulputate, semper eros sed, auctor ligula. Duis orci orci, viverra eu porta sed, pharetra nec augue. Duis in urna porttitor, auctor mi scelerisque, adipiscing nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent venenatis pulvinar venenatis. Fusce turpis neque, malesuada id feugiat non, dignissim eu dui. Sed egestas arcu id nibh rhoncus molestie. Vivamus interdum, libero a consectetur posuere, tellus sapien consequat augue, sit amet dignissim eros sapien et sem.'),
('Nulla eu tincidunt magna. Curabitur congue, urna sed sodales malesuada, massa est accumsan metus, ut pharetra est lectus ultrices sapien. Duis ultricies placerat libero sit amet ultricies. Etiam mattis orci ut venenatis dignissim. Sed condimentum cursus mi, sit amet gravida lorem hendrerit in. Donec fermentum sem mauris, vel rhoncus elit tristique sit amet. Sed lacus diam, laoreet id tincidunt pulvinar, commodo a nibh. Maecenas euismod cursus suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce laoreet metus sed mollis egestas. Integer elementum mollis magna a ultrices. Morbi eget velit libero. Vestibulum lacinia odio volutpat, viverra magna vitae, mollis risus. Integer sed egestas dolor.'),
('Maecenas pharetra orci id lacus pellentesque, non rutrum nunc tristique. Donec sagittis, lacus sit amet fermentum elementum, dui metus tincidunt arcu, ut luctus purus ante luctus nulla. Quisque eu nisi non nibh vehicula sagittis. Vestibulum luctus lectus elit, quis gravida nulla faucibus pulvinar. Cras eget interdum nisi, ut vestibulum enim. Quisque eget diam nec felis facilisis fermentum. Donec sit amet massa tempus, pretium risus vitae, tristique mauris. Integer vel lorem at dui iaculis malesuada. Mauris bibendum enim posuere nisl laoreet, eu sollicitudin dolor commodo. Donec mi quam, facilisis consectetur nunc sit amet, convallis cursus quam. Aliquam sit amet scelerisque nibh. Pellentesque quam neque, elementum id consectetur quis, egestas lobortis sem.'),
('Sed vestibulum nisi ipsum, laoreet mollis turpis tincidunt molestie. Curabitur nec metus et lorem mollis fermentum ac sit amet elit. In hac habitasse platea dictumst. In ullamcorper eros id nisi porta adipiscing. Mauris bibendum fermentum sapien in fermentum. Aliquam nec interdum diam, a consectetur augue. Etiam ut bibendum diam, sit amet fermentum velit. Curabitur a ante eu urna auctor molestie in at diam. Proin mattis arcu nunc, non tincidunt nulla faucibus sed. Phasellus fringilla, massa id consequat feugiat, mi lectus varius augue, a adipiscing elit purus venenatis diam. Mauris id velit consequat, accumsan dolor nec, suscipit quam. Vestibulum eget tristique urna. Nulla tempus, dui ut eleifend consequat, justo ipsum iaculis nibh, in congue dui dolor quis dolor. Cras quis turpis vel quam convallis blandit a vitae nunc.'),
('Cras tortor magna, pulvinar ut metus at, dignissim pharetra orci. Donec et neque hendrerit, lacinia dui ac, pretium purus. Pellentesque eros sapien, placerat sed pellentesque quis, sollicitudin vulputate orci. In sodales justo dui, quis malesuada neque tincidunt ac. Aenean non velit id neque sollicitudin suscipit. Vestibulum vulputate nunc at tortor posuere tempor. Duis in aliquam magna. In pharetra, eros sed luctus rhoncus, libero erat rhoncus nisl, nec ultricies neque leo at odio. Curabitur id lorem id tortor pulvinar molestie. Curabitur cursus eleifend dui.'),
('Morbi blandit sem eget aliquam scelerisque. In gravida consequat velit, ac consequat purus tincidunt vitae. Donec erat velit, laoreet id arcu non, viverra vehicula lorem. Vivamus id malesuada nunc. Vestibulum enim diam, gravida non imperdiet adipiscing, mattis ac felis. Ut luctus volutpat felis a aliquet. Aliquam vel congue quam.'),
('Donec ultricies leo in nulla laoreet aliquam. Fusce enim nulla, euismod at lorem ut, pulvinar viverra mauris. Aliquam vitae pellentesque mauris, sit amet fermentum libero. Aliquam erat volutpat. Etiam quis ipsum metus. Praesent bibendum scelerisque velit vitae ullamcorper. Fusce a arcu sed augue iaculis hendrerit. Morbi sit amet dolor faucibus, suscipit ante sit amet, ullamcorper magna. Mauris sit amet lectus sed tellus cursus lobortis. Sed commodo nec enim vitae auctor. Cras commodo hendrerit nulla, sit amet ornare elit suscipit vel. Phasellus ut ante eros. Aliquam eleifend lacinia mi in cursus. Aliquam porta ornare mi, id convallis mi tincidunt et.'),
('Etiam porttitor, nisl non auctor hendrerit, augue purus tempor sapien, sit amet ornare risus lorem ut nunc. In eu mattis elit. Phasellus pharetra augue et tincidunt fermentum. Cras hendrerit neque non ornare posuere. Sed pulvinar adipiscing nulla et porttitor. Fusce aliquet pharetra urna. Sed venenatis tellus non pretium ullamcorper.'),
('Suspendisse ut accumsan dolor. Sed quis dui pulvinar, sodales libero et, interdum massa. Vivamus vulputate commodo sagittis. Aenean ac diam sed sapien ultricies commodo. Nam sagittis mi ut arcu dapibus, in pulvinar mauris consequat. Donec varius porta nibh, id feugiat arcu ultricies et. Donec quis metus non metus vestibulum porttitor ac ut mauris. Fusce auctor ipsum sit amet sollicitudin pretium. Integer porta mi rutrum mauris suscipit, nec pharetra metus sagittis. Duis eget neque et massa laoreet tempor nec vel urna. Sed id justo vel tortor tincidunt porta. Sed posuere sapien risus, sit amet tincidunt magna varius vitae. Etiam tincidunt, orci ut aliquet aliquet, nunc tortor imperdiet nisi, vitae egestas est risus ut ligula. Donec mollis aliquam urna, ut ullamcorper tellus tincidunt ac. Cras tempor pretium mauris, vitae vulputate odio tincidunt vel.'),
('Donec sit amet ante vel neque gravida cursus. Sed consectetur, neque sed pulvinar imperdiet, diam urna faucibus nibh, a molestie erat nisl at lacus. Mauris sapien ante, interdum porttitor orci a, vulputate auctor magna. Pellentesque nec leo eu ligula fermentum facilisis vel lobortis ligula. Curabitur ac erat sit amet felis eleifend egestas non sit amet tellus. Nunc pulvinar, lacus vitae dictum volutpat, erat elit porta dui, id pulvinar orci ante ut turpis. Phasellus aliquet lectus vel est tempor, ut laoreet nibh pharetra. Suspendisse accumsan lacus vel tincidunt elementum. Aenean ligula sem, congue id nulla a, auctor faucibus est. Ut sodales vestibulum enim et congue. Donec et fermentum dui. Curabitur et risus lorem. Praesent risus enim, gravida non eros at, tristique venenatis est. Nunc hendrerit mauris tortor, non luctus lectus lobortis non. Pellentesque vel leo sit amet ligula aliquam sollicitudin. In hac habitasse platea dictumst.'),
('Curabitur at convallis velit, in lobortis ligula. Vivamus in gravida velit, eu rhoncus nunc. Quisque molestie sem in faucibus sagittis. Nulla mi sem, luctus vitae imperdiet eu, pellentesque sit amet odio. In pulvinar justo sed interdum ultrices. Aliquam libero lectus, suscipit id malesuada rutrum, laoreet scelerisque nulla. Donec pretium justo sit amet est sagittis, vitae tincidunt ante varius. Proin iaculis leo ut leo consequat ultrices. Fusce mattis a nulla et dictum. Etiam vitae velit pellentesque, gravida justo at, sagittis libero. Proin rutrum, elit porttitor condimentum consectetur, mi justo pharetra turpis, non tempor purus nisl eu purus. Curabitur pellentesque scelerisque orci. Nulla ultrices ornare congue. Nullam nisl nibh, lacinia quis lectus a, blandit porttitor enim. Ut eu lorem ut enim molestie ultricies ut at quam. Suspendisse vulputate vitae ante nec scelerisque.'),
('Proin at est urna. Aliquam vitae leo enim. Fusce nunc felis, convallis et lectus malesuada, lacinia volutpat urna. Vestibulum tincidunt, nulla blandit ullamcorper feugiat, sapien tortor condimentum lorem, nec sodales quam augue at odio. Donec tempor imperdiet eros, non elementum elit. Etiam non leo sit amet sapien ultrices consequat quis a odio. Mauris justo elit, tincidunt eget semper pretium, sodales sed quam. Sed sollicitudin sem velit, venenatis tincidunt dui porttitor dapibus. Aliquam sed iaculis nulla. Suspendisse rhoncus vel velit sit amet luctus. Vestibulum id diam ac elit placerat fringilla. In at sapien commodo, fringilla nisl adipiscing, egestas sem.'),
('Nunc sed tellus purus. Phasellus vitae gravida risus, ut rhoncus arcu. Etiam vitae ligula sem. Integer a tortor eu nisl rutrum tempus. Duis suscipit nulla vitae molestie interdum. Sed a placerat massa. Integer ut purus ac odio vestibulum interdum sit amet id lacus. Nullam pretium, nunc at hendrerit ultricies, risus eros ultrices lacus, at ullamcorper leo augue at odio. Praesent nec erat id neque dignissim iaculis. Integer ac sapien libero.'),
('Donec vel dui libero. Maecenas euismod, mi sit amet condimentum sodales, odio nulla cursus odio, a dictum nibh libero posuere mauris. Quisque quis quam eget arcu tincidunt interdum id ut odio. Nulla egestas ut eros eu egestas. Fusce ut vestibulum magna. Suspendisse aliquam quis quam eget lobortis. Integer risus elit, auctor vel venenatis non, tempor ac felis. Aliquam quis eleifend leo. Vestibulum pretium pulvinar dui malesuada commodo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce urna augue, congue vel congue id, fringilla sit amet nisl. Nunc tincidunt lorem eu porttitor auctor. Ut purus nisi, dictum quis tortor ac, auctor ornare ante. Proin neque elit, auctor in felis iaculis, laoreet vulputate mauris. In aliquet, libero pharetra blandit dignissim, augue ante consequat ipsum, id convallis nunc erat quis est. Praesent porta ultrices justo, nec hendrerit felis porta ac.'),
('Fusce tincidunt posuere justo, non bibendum dui dictum sit amet. Fusce eget magna eu urna elementum viverra. Duis dolor ante, vestibulum id nisl eget, mollis vehicula velit. Morbi tempus, sem nec imperdiet accumsan, nibh elit interdum ipsum, lacinia iaculis odio augue eu nisi. Phasellus a nibh quam. Phasellus pulvinar commodo dui, sit amet commodo enim commodo sed. Maecenas posuere turpis vitae neque pharetra gravida. Curabitur metus leo, mattis sit amet tellus ut, vulputate adipiscing sapien. Curabitur convallis pulvinar sapien. Cras eu ipsum dictum, ultrices neque in, faucibus velit.'),
('Cras euismod suscipit erat, et iaculis lectus ullamcorper nec. Proin et felis eu elit lobortis vulputate. Pellentesque eget leo non dolor malesuada ornare eget quis risus. Pellentesque eu posuere urna, a lacinia odio. Curabitur pulvinar et massa ut egestas. Nunc ullamcorper enim id turpis ornare blandit. Integer non eros et lacus ornare aliquet quis in velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin scelerisque tellus at suscipit varius.'),
('Aliquam vulputate, metus eu ornare ornare, nisl magna sollicitudin diam, a pretium leo nisi non sapien. Nunc convallis mi in sodales egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur iaculis mi sed metus congue, ac adipiscing nisl pretium. Quisque porta libero non nunc ullamcorper, quis vulputate tellus scelerisque. Sed vitae velit ullamcorper, dignissim nunc suscipit, condimentum eros. Praesent tincidunt mattis auctor. Vestibulum scelerisque sapien ut lorem iaculis, ac vulputate felis sagittis.'),
('Donec eget ipsum erat. Proin sagittis nisi varius lorem dictum pretium. Quisque mollis vehicula sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet scelerisque magna. Nunc egestas tellus odio, nec vestibulum sem viverra vel. Curabitur condimentum, eros ut ultrices imperdiet, turpis arcu tristique tortor, at consectetur ipsum nisi a ipsum.'),
('Nulla vestibulum elementum est, ut sollicitudin orci condimentum et. Nulla facilisi. Proin odio velit, rhoncus convallis tincidunt ac, adipiscing sit amet ipsum. Integer in quam urna. Nunc nec tortor felis. Curabitur viverra varius arcu a consequat. Pellentesque molestie libero at ligula varius, a adipiscing turpis egestas. Nunc venenatis leo ac sapien aliquet consectetur.'),
('Suspendisse porttitor dapibus erat, eu convallis dolor vestibulum pharetra. Sed nec lacinia mauris, id porttitor lectus. Sed felis sem, fringilla quis mollis in, placerat et leo. Sed pretium eros risus, vel aliquam neque pharetra sed. Pellentesque nec est fringilla, bibendum lacus a, imperdiet orci. Nunc eget vestibulum diam, vitae consectetur nunc. Donec ut erat elementum, blandit felis eu, dignissim sem. Aenean sodales velit quis dolor scelerisque, non facilisis dui accumsan. Curabitur bibendum neque a arcu tincidunt suscipit. Cras ullamcorper nulla sem, in consequat lacus posuere quis. In aliquet a enim vel tristique. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam feugiat lacus sit amet fringilla fermentum.'),
('Suspendisse tellus quam, placerat id scelerisque et, cursus at justo. Vivamus mauris turpis, pulvinar sit amet viverra ut, gravida at sapien. Cras sit amet tincidunt odio. Morbi blandit metus justo, sed condimentum leo consectetur eu. Mauris laoreet tortor enim, quis ullamcorper nibh sagittis eu. Suspendisse eleifend, lectus ac dignissim pellentesque, arcu enim viverra tellus, quis cursus lacus felis id sem. Aliquam vestibulum non quam vitae feugiat. Mauris varius ante ac bibendum iaculis. Nunc pellentesque vitae neque a ullamcorper. Donec ut risus lacus. Morbi lacinia commodo nulla eu rhoncus. Suspendisse et tempor nisi. Quisque facilisis consequat mi sit amet fermentum. Sed dictum diam urna, malesuada dapibus turpis accumsan quis.'),
('Aliquam pretium eleifend dignissim. Ut ac lacinia mauris, et porttitor mi. Proin nisi mauris, ornare a lorem ac, adipiscing vulputate felis. Aenean feugiat magna dolor, vitae ultrices magna tempus a. Etiam in sapien tempor, dictum lacus sed, imperdiet quam. Nullam neque felis, dignissim vel posuere sed, interdum sed turpis. Phasellus turpis risus, porttitor et sodales sed, luctus eget leo. Mauris sagittis placerat condimentum. Integer ullamcorper diam et porttitor molestie.'),
('Pellentesque feugiat congue sem, a lacinia odio mattis consequat. Integer sed velit risus. Ut eleifend magna lacus, id rhoncus enim condimentum quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin convallis adipiscing elementum. Donec vel odio eget dui dignissim pharetra eget a odio. Phasellus sit amet blandit arcu. Sed a hendrerit tellus, eu viverra mauris. Aenean auctor hendrerit elit, placerat malesuada lorem sagittis nec. Mauris ut consectetur nisi, et tempus turpis. Fusce sed elit leo. Fusce hendrerit pulvinar lacus in pretium.'),
('Mauris eros risus, pharetra ac ipsum sed, rutrum varius magna. Mauris ac eros gravida est vulputate pharetra. Sed dignissim non ipsum tincidunt vehicula. Morbi sodales tempus tortor, sodales pellentesque libero semper ac. Sed erat.');
	
	